# Generated by Django 4.1.6 on 2023-02-09 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_car'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Car',
        ),
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.CharField(default='автор', max_length=30),
            preserve_default=False,
        ),
    ]
