# Generated by Django 4.1.6 on 2023-02-22 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_book_readers_alter_book_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbookrelation',
            name='rate',
            field=models.PositiveSmallIntegerField(choices=[(1, 'bad'), (2, 'ok'), (3, 'norm'), (4, 'good'), (5, 'incredible')], null=True),
        ),
    ]
