# Generated by Django 4.1.6 on 2023-03-10 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_alter_userbookrelation_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='rating',
        ),
    ]
